export const DECK_OUTLINE_PLANNING_PORT = Symbol("DECK_OUTLINE_PLANNING_PORT");
export const DESIGN_PLANNING_PORT = Symbol("DESIGN_PLANNING_PORT");
export const SEMANTIC_SEGMENTATION_ADAPTER = Symbol("SEMANTIC_SEGMENTATION_ADAPTER");
export const SEMANTIC_SEGMENTER_PORT = Symbol("SEMANTIC_SEGMENTER_PORT");
export const SEMANTIC_SEGMENTATION_REPAIRER_PORT = Symbol("SEMANTIC_SEGMENTATION_REPAIRER_PORT");
export const LLM_RUNTIME_CONFIG = Symbol("LLM_RUNTIME_CONFIG");
export const LLM_COMPLETION_CLIENT = Symbol("LLM_COMPLETION_CLIENT");
