export const PPTX_EXPORT_JOB_STORE = Symbol("PPTX_EXPORT_JOB_STORE");
export const PPTX_EXPORT_JOB_RUNNER = Symbol("PPTX_EXPORT_JOB_RUNNER");
export const PPTX_QUEUE_CONFIG = Symbol("PPTX_QUEUE_CONFIG");
export const PPTX_ARTIFACT_STORE = Symbol("PPTX_ARTIFACT_STORE");
export const PPTX_BROWSER_FACTORY = Symbol("PPTX_BROWSER_FACTORY");
